

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/apps/incident-api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "terraform"
    directory: "/terraform/environments/dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/apps/incident-api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"