name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build-incident-api-image:
    name: Build Incident API Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build Docker image
        run: |
          docker build \
            -t incident-api:ci \
            apps/incident-api
