name: Platform CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  helm:
    name: Validate Helm chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Helm
        uses: azure/setup-helm@v5
        with:
          version: "v3.18.3"

      - name: Lint Helm chart
        run: helm lint helm/incident-api

      - name: Render Helm manifests
        run: helm template incident-api helm/incident-api

  terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform formatting
        run: terraform fmt -recursive -check

      - name: Initialize Terraform
        run: terraform init -backend=false

      - name: Validate Terraform
        run: terraform validate
